package main

func OaQ7ml0() string {
	return string(
		[]byte{
			((eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax() ^ eax()) << eax() << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()) << eax() << eax() << eax(),
			(eax()<<eax() | eax()) << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			(((eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()) << eax() << eax() << eax(),
			(eax()<<eax() | eax()) << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
		},
	)
}

func UNCbua1() string {
	return string(
		[]byte{
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
		},
	)
}

func M2oYBh2() string {
	return string(
		[]byte{
			(((eax()<<eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()),
			((eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()) << eax(),
			((eax()<<eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((((eax()<<eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(eax()<<eax()<<eax()<<eax() | eax()) << eax() << eax() << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			(((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax() ^ eax()),
		},
	)
}

func J3haXV3() string {
	return string(
		[]byte{
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()) << eax(),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()^eax())<<eax() ^ eax()) << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax() << eax(),
		},
	)
}

func Nv1LGH4() string {
	return string(
		[]byte{
			(((eax()<<eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()) << eax() << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()),
			((eax()<<eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()),
			((eax()<<eax()<<eax()|eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax() ^ eax()),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((eax()<<eax()<<eax()<<eax()<<eax()|eax())<<eax() ^ eax()) << eax(),
			((eax()<<eax()<<eax()|eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			((((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax()^eax())<<eax() ^ eax()),
			(((eax()<<eax()<<eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()),
			eax() << eax() << eax() << eax() << eax() << eax(),
			((((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()^eax())<<eax() ^ eax()) << eax(),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax()^eax())<<eax() ^ eax()),
			(eax()<<eax()<<eax() | eax()) << eax() << eax() << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()),
			((((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()^eax())<<eax() ^ eax()) << eax(),
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax() ^ eax()) << eax() << eax(),
			(((eax()<<eax()|eax())<<eax()<<eax()<<eax()^eax())<<eax()<<eax() ^ eax()),
		},
	)
}
